### ISSUE TITLE
Recompile dll without including UnlimtedLog to avoid log spam

### ISSUE THREAD

**Issue by fluff-li** [llunak/rimworld-moreprecepts#6]
![moreprecepts_decompiled](https://user-images.githubusercontent.com/56023678/230773294-c93a20e1-8842-420f-b10b-e0f5bb9d8c85.PNG)
![moreprecepts_spam](https://user-images.githubusercontent.com/56023678/230773297-e152ec89-6797-467d-8669-3d249130bfa4.PNG)

**Comment by llunak** [comment]
Oops, that's indeed not supposed to be there, thanks.
